FROM python:3.13-slim

WORKDIR /workspace
COPY requirements-docs.txt /tmp/requirements-docs.txt
RUN pip install --no-cache-dir -r /tmp/requirements-docs.txt

CMD ["mkdocs", "serve", "--dev-addr=0.0.0.0:8000"]

